# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e6f92bc873b661ac3064c125da61d1299d1b9c6ae370b3381b8fd814d0405f88c20b9f9515a4bfaf190d802687a429343390238778a63bb488f26376359f280

test:
  secret_key_base: 7af2bdc9a36bef915176fcd865d96bb68865cffe8bb1cf9c23f1ad6f876508d98663d09b725cc2478c4fd2124eb6d484d6309a9d12834c1efb5fb449273b48fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
